### PR TITLE
Update lodash.difference to 4.5.0

### PR DESCRIPTION
**Pull request by classicsman**
Signed-off-by: Ricky Gleitz <classicsman@gmail.com>

### CODE REVIEW

**Comment by classicsman** [comment]
Hi Devon,

Hacktoberfest has a note for me that says Lodash is not participating. Is
this something that can be fixed?

Thanks,

Rick Gleitz

**Comment by InfoSec812** [comment]
I believe it is fixed now.

Deven

**Comment by classicsman** [comment]
Hi Devon,

The Hacktoberfest site still says 'Non-participating.' Does it take a while
to update?

Thanks again.

Rick Gleitz

**Comment by classicsman** [comment]
Hi Devon,

Looks like it's in! Just gotta go thru the seven-day waiting period. Thanks
so much!

Rick Gleitz

**Comment by InfoSec812** [comment]
Yay! Glad it worked finally!

**Pull request merged**
